name: Scrape latest Cisa Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data from Cisa
      run: |-
        curl -O https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json
    - name: Check if Valid JSON
      run: |-
        json_data=```cat known_exploited_vulnerabilities.json```
        set +e
        retval=$(jq -re '""' <<<"${json_data}" 2>&1)
        if [ -z "${retval}" ]; then
          echo "JSON validation successful"
        else
          echo "ERROR: jq - ${retval}"
          exit ${retval}
        fi


    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push